In [7]:
import pandas as pd
import numpy as np
from IPython.display import display

np.random.seed(42)

# Series

### Ejercicio 1: crea e inspecciona una Series

1. Crea una Series llamada `temperatures` con los valores `18, 21, 19, 24`.
2. Usa como índice `"Mon", "Tue", "Wed", "Thu"`.
3. Muestra el valor de `"Wed"`.
4. Muestra su índice y sus valores.

In [ ]:
temperatures = pd.Series([18,21,19,24],["Mon", "Tue", "Wed", "Thu"])
print("Serie temperaturas:\n",temperatures)
print("Valor de Wed: ", temperatures["Wed"])
print("Indices: \n", temperatures.index)
print("Valores: \n", temperatures.values)

# DataFrames

### Ejercicio 1: Crea un DataFrame manualmente

Crea un DataFrame llamado `df_products` con estas columnas:
    - `Product`
    - `Price`
    - `Stock`

Usa al menos 4 filas.
Después:
  1. muéstralo,
  2. imprime `shape`,
  3. imprime solo los nombres de columnas.

In [60]:
datasetmanual = {
    'Product': ['Phone', 'Laptop', 'Teclado', 'Mouse'],
    'Price': [25, 30, 35, 40],
    'Stock': [50, 40, 70,90],
}
df_products = pd.DataFrame(datasetmanual)

print("DataFrame Products:\n",df_products)
print("Shape(t_filas,t_columnas):",df_products.shape)
print("Columnas:\n",df_products.columns)

DataFrame Products:
    Product  Price  Stock
0    Phone     25     50
1   Laptop     30     40
2  Teclado     35     70
3    Mouse     40     90
Shape(t_filas,t_columnas): (4, 3)
Columnas:
 Index(['Product', 'Price', 'Stock'], dtype='str')

### Ejercicio 2: Crear DataFrames con ficheros externos

Cargar un fichero csv y leer los datos

1. Carga `personas.csv` en un DataFrame llamado `people_csv`.
2. Carga `personas.json` en un DataFrame llamado `people_json`.
3. Muestra `shape` de ambos.
4. Muestra las 2 primeras filas de cada uno.

In [61]:
people_csv = pd.read_csv('../Introduccion_Pandas/parte 1/personas.csv')
print("DataFrame personas.csv")
display(people_csv)
print("people_csv.shape(t_filas, t_columnas)", people_csv.shape)
display("Primeras 2 filas",people_csv.head(2))

people_json = pd.read_json('../Introduccion_Pandas/parte 1/personas.json')
print("DataFrame people_json")
display(people_json)
print("people_json.shape(t_filas, t_columnas)", people_json.shape)
display("Primeras 2 filas",people_json.head(2))

DataFrame personas.csv

  Nombre  Edad        Ciudad
0    Ana    25          Lima
1   Luis    30        Bogotá
2  María    22  Buenos Aires

people_csv.shape(t_filas, t_columnas) (3, 3)

'Primeras 2 filas'

  Nombre  Edad  Ciudad
0    Ana    25    Lima
1   Luis    30  Bogotá

DataFrame people_json

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]
2  María    22             [arte, cine]

people_json.shape(t_filas, t_columnas) (3, 3)

'Primeras 2 filas'

  nombre  edad                intereses
0    Ana    25  [lectura, programación]
1   Luis    30       [deportes, música]

### Ejercicio 3: Mostrar informacion del DataFrame

Usando `df_large`:
1. muestra las 5 primeras filas,
2. muestra las 5 últimas,
3. imprime `shape`,
4. imprime solo el número de filas usando `shape[0]`,
5. imprime `dtypes`(tipo de dato de cada columna).

In [78]:
values = np.random.randint(0, 100, size=(100, 5)) # genera una matriz (array) de NumPy de números enteros aleatorios.
df_large = pd.DataFrame(values, columns=['A', 'B', 'C', 'D', 'E'])

display("Primeras 5 filas",df_large.head(5))
display("Ultimas 5 filas",df_large.tail(5))
print("df_large.shape(t_filas, t_columnas)", df_large.shape)

print("Total de Filas:", df_large.shape[0])
print("Total de Columnas:", df_large.shape[1])
print("Dtypes: \n", df_large.dtypes)

'Primeras 5 filas'

    A   B   C   D   E
0  83  14  92   7  40
1  18  45  27  90  67
2  14  98  36   0  66
3  23  26  39  62  60
4  35  97  92  23  23

'Ultimas 5 filas'

     A   B   C   D   E
95  67  11  59  26  55
96  22  24  20  60  62
97  51  87  24  54  45
98  31  54  95   4  35
99  48  57  38  79  96

df_large.shape(t_filas, t_columnas) (100, 5)
Total de Filas: 100
Total de Columnas: 5
Dtypes:
 A    int32
B    int32
C    int32
D    int32
E    int32
dtype: object

### Ejercicio 4: Seleccionar elementos en el dataframe

Usando `df_large`:
1. selecciona las columnas `B` y `E`,
2. muestra las filas 50 a 55 usando `.iloc`,
3. muestra el valor de la fila `0` y la columna `A` usando `.loc`,
4. selecciona filas 10 a 15 y columnas `C` y `D`.

In [63]:
display("Columnas B y E", df_large[['B','E']])
display("Filas de la 50 a 55", df_large.iloc[50:56])
display("Fila 0 Columna A: ", df_large.loc[0,'A'])
display("Filas de la 10 a 15, Columnas C y D ", df_large.loc[10:15,'C':'D'])

'Columnas B y E'

     B   E
0   89  30
1   38  86
2   54  52
3   64  52
4   20  18
..  ..  ..
95  97  67
96  10  20
97  75  59
98  46  39
99  20  22

[100 rows x 2 columns]

'Filas de la 50 a 55'

     A   B   C   D   E
50  99  76   6  99  50
51  72  31  74   7  96
52  86  88  71  44  85
53  58   3  66  28  28
54  97  97  27  76  78
55  86  43  89   3  89

'Fila 0 Columna A: '

np.int32(65)

'Filas de la 10 a 15, Columnas C y D '

     C   D
10  76  58
11  11  30
12  97  74
13  56  94
14  95  85
15  87  49

### Ejercicio 5: Filtrar utilizando máscaras y crear columnas nuevas
mask(condiciones, pueden ser simples o con varias condiciones)

Usando `df_large`:
1. crea una columna `Total_AB` con `A + B`,
2. filtra filas con `A > 50`,
3. filtra filas con `A > 50` y `B < 20`,
4. muestra solo las columnas `A`, `B` y `Total_AB` del resultado filtrado.

In [ ]:
df_large['Total_AB'] = df_large['A'] + df_large['B']
display("Nueva Columna Total_AB", df_large.head)
mask_simple = df_large['A']>50
display("Columnas donde A>50", df_large[mask_simple].head(5))
mask_varias = (df_large['A']>50) & (df_large['B']<20)
display("Columnas donde A>50 y B<20", df_large[mask_varias].head)

display("Solo Columnas A, B y Total_AB", df_large[['A', 'B', 'Total_AB']])

### Ejercicio 6: Ordena resultados por columnas de forma ASC o DESC
ASC(por defecto, ordena de menor a mayor) o DESC(de mayor a menor)

1. Ordena `df_large` por la columna `C` de mayor a menor.
2. Ordena `df_large` por `B` descendente y `D` ascendente.
3. Muestra las 5 primeras filas de cada resultado.

In [ ]:
display("Ordenar por Columna C - DESC(de mayor a menor)", df_large.sort_values(by='C', ascending=False).head(5))
display("Ordenar por Columna B-DESC y D-ASC", df_large.sort_values(by=['B','D'], ascending=[False,True]).head(5))

## 🏆 Práctica Final. Parte 1

Usando `df_large`:

1. Crea una nueva columna llamada `Suma` que sea `A + B`.
2. Filtra las filas donde `Suma` sea mayor a `100`.
3. Quédate solo con las columnas `A`, `B`, `C` y `Suma`.
4. Ordena el resultado por la columna `C` de forma descendente.
5. Guarda el resultado en un archivo `resultado.csv`.

In [83]:
df_large['Suma'] = df_large['A'] + df_large['B']
display("Nueva columna Suma",df_large.head(5))
display("Filas Suma>100",df_large[df_large['Suma']>100].head(5))
display("Solo columnas A,B,C, Suma",df_large[['A','B','C','Suma']].head(5))

'Nueva columna Suma'

    A   B   C   D   E  Suma
0  83  14  92   7  40    97
1  18  45  27  90  67    63
2  14  98  36   0  66   112
3  23  26  39  62  60    49
4  35  97  92  23  23   132

'Filas Suma>100'

    A   B   C   D   E  Suma
2  14  98  36   0  66   112
4  35  97  92  23  23   132
6  86  52  22  68  94   138
7  52  61  40  56  59   113
8  53  69  56   9  39   122

'Solo columnas A,B,C, Suma'

    A   B   C  Suma
0  83  14  92    97
1  18  45  27    63
2  14  98  36   112
3  23  26  39    49
4  35  97  92   132